### ISSUE TITLE
Have a rust crate?

### ISSUE THREAD

**Issue by Maple0817** [svg-rust/svgr-rs#16]
Could have a rust crate to revert svg to JS code? just like svgr.

**Comment by SyMind** [comment]
@Maple0817  Sorry, busy with work, I replied so late. I will release the rust package this week.

**Comment by Maple0817** [comment]
Cool! Many thanks for that

**Comment by Maple0817** [comment]
Any update for this？

**Comment by SyMind** [comment]
@Maple0817 I published first version: https://crates.io/crates/svgr-rs .

**Comment by Maple0817** [comment]
the crate can not be used. 
When I add it in toml, add use svgr_rs in rs; no external crate `svgr_rs` is happened.
Meanwhile, could you provide a sample code that how to use the crate in rust? seems the config is also not public.
