### ISSUE TITLE
Config looks like not working

### ISSUE THREAD

**Issue by JiangWeixian** [svg-rust/svgr-rs#6]
I create a plugin https://github.com/JiangWeixian/svgrs-plugin used in vite&webpack,  I transform code like this:

```tsx
const raw = await fs.readFile(cleanUrl(id), 'utf-8')
let svgrsCode = await transform(
  raw,
  { namedExport, exportType, jsxRuntime, icon, ...config },
  {
    componentName: namedExport,
    filePath: id,
    caller: {
      previousExport: code,
      name: 'svgrs-plugin/vite',
    },
  },
)
```

If I define `namedExport: "ReactComponent"`, always `export default ReactComponent`

**Comment by SyMind** [comment]
@JiangWeixian I released 0.0.8 version for svgr-rs. It has supported most configurations except for svgo and prettier.
If you are willing, you can move your project to the `svg-trust` organization.

**Comment by JiangWeixian** [comment]
> @JiangWeixian I released 0.0.8 version for svgr-rs. It has supported most configurations except for svgo and prettier. If you are willing, you can move your plugin to the `svg-rust` organization.

Sure, what should I do?

**Comment by SyMind** [comment]
@JiangWeixian I have invited you to join the `svg-rust` organization and you will receive an email.

**Comment by SyMind** [comment]
@JiangWeixian I have invited you to join the `svgr-rs` organization in npm too.

**Comment by JiangWeixian** [comment]
@SyMind Cool, I already try to import old svgrs-plugin repo into this organization. Waiting for import finish...

**Comment by JiangWeixian** [comment]
@SyMind Could you enable organization level permissions to let github actions create and approve prs(https://stackoverflow.com/questions/72376229/github-actions-is-not-permitted-to-create-or-approve-pull-requests-createpullre). Which is required by `changsets/actions`, I use it to automatic publish npm packages.

**Comment by SyMind** [comment]
@JiangWeixian I has enabled it.
